"""Phase 11 — `artifacts/figures/INDEX.md`, written from what the figures recorded.

    python -m app.research.figure_index [--check]

`plotstyle.save` appends one row per figure to `artifacts/figures/manifest.jsonl`
— the caption the figure carries on its own face, the script that drew it and
the files that script reads. This renders those rows as the index, newest write
per figure winning, and enforces two rules while it does:

* **Provenance.** A PNG on disk with no manifest row is listed as stale, because
  either it was drawn before this phase or its script no longer produces it.
* **No figure reads what is not in the repository's data.** Every declared
  source must exist and live under `artifacts/`, `data/`, or one of the two
  checked-in inputs that a *schema* illustration legitimately reads
  (`ALLOWED_ROOTS`). ``--check`` exits non-zero instead of writing.
"""
from __future__ import annotations

import argparse
import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
FIGURE_ROOT = ROOT / "artifacts" / "figures"
MANIFEST = FIGURE_ROOT / "manifest.jsonl"
INDEX = FIGURE_ROOT / "INDEX.md"

#: Where a figure is allowed to read from. `artifacts/` and `data/` are results
#: and data; the last two are checked-in *inputs* that the Phase 1 and Phase 2
#: figures illustrate — the item bank's concept graph and one recorded telemetry
#: fixture. Neither carries a result.
ALLOWED_ROOTS = ("artifacts/", "data/", "backend/src/data/",
                 "ml-service/app/features/testdata/")

PHASE_TITLES = {
    "01-content": "Phase 1 — item bank and content",
    "02-telemetry": "Phase 2 — the telemetry instrument",
    "03-archival": "Phase 3 — archival datasets",
    "04-simulator": "Phase 4 — the calibrated simulator",
    "05-eda": "Phase 5 — features and exploratory analysis",
    "06-study1": "Phase 6 — Study 1, prediction and the ablation ladder",
    "07-study2": "Phase 7 — Study 2, state heads and the validity gate",
    "08-policies": "Phase 8 — Study 4, the simulated closed loop",
    "08.5-integration": "Phase 8.5 — the integration gate",
    "09-ope-rl": "Phase 9 — Study 3, off-policy evaluation and RL",
    "10-system": "Phase 10 — the deployed platform",
    "11-stats": "Phase 11 — statistics and sensitivity",
    "12-walkthrough": "Phase 12 — end-to-end walkthrough",
}


def read_manifest() -> "OrderedDict[tuple[str, str], dict]":
    entries: OrderedDict[tuple[str, str], dict] = OrderedDict()
    if not MANIFEST.exists():
        return entries
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        entries[(row["directory"], row["figure"])] = row     # last write wins
    return entries


def check_sources(entries: dict) -> list[str]:
    problems = []
    for (directory, figure), row in entries.items():
        for source in row.get("sources", []):
            if not source.startswith(ALLOWED_ROOTS):
                problems.append(f"{directory}/{figure}: reads {source}, which is outside "
                                f"{', '.join(ALLOWED_ROOTS)}")
            elif not (ROOT / source).exists():
                problems.append(f"{directory}/{figure}: declares {source}, which does not exist")
        if not row.get("sources"):
            problems.append(f"{directory}/{figure}: declares no source file "
                            f"(add SOURCES to {row.get('script', 'its script')})")
    return problems


def render(entries: dict) -> str:
    on_disk = {(str(path.parent.relative_to(FIGURE_ROOT)), path.name)
               for path in FIGURE_ROOT.glob("*/*.png")}
    lines = [
        "# Figure index",
        "",
        "Every figure in this project, with the caption it carries, the script that "
        "draws it and the files that script reads. Generated by "
        "`python -m app.research.figure_index` from `manifest.jsonl`, which "
        "`app.research.plotstyle.save` appends to at render time — so a caption here "
        "is the figure's own, not a transcription. Regenerate the whole pack with "
        "`make figures`.",
        "",
        f"{len(entries)} figures recorded. Each is written as a 300 DPI PNG and a "
        "vector PDF of the same name.",
        "",
    ]
    for directory in sorted({key[0] for key in entries} | {key[0] for key in on_disk}):
        rows = {key[1]: value for key, value in entries.items() if key[0] == directory}
        stale = sorted(name for name in
                       {key[1] for key in on_disk if key[0] == directory} - set(rows))
        lines += [f"## {PHASE_TITLES.get(directory, directory)}", "",
                  "| Figure | Caption | Script | Reads |", "|---|---|---|---|"]
        for figure in sorted(rows):
            row = rows[figure]
            caption = (row.get("caption") or "—").replace("|", "\\|")
            sources = "<br>".join(f"`{source}`" for source in row.get("sources", [])) or "—"
            lines.append(f"| `{figure}` | {caption} | `{row.get('script', '?')}` | {sources} |")
        for figure in stale:
            lines.append(f"| `{figure}` | **stale** — on disk with no manifest row; "
                         f"rerun `make figures` | — | — |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify provenance and write nothing")
    args = parser.parse_args()

    entries = read_manifest()
    if not entries:
        raise SystemExit(f"{MANIFEST.relative_to(ROOT)} is empty — run `make figures` first")
    problems = check_sources(entries)
    for problem in problems:
        print(f"  {problem}")
    if problems:
        raise SystemExit(f"{len(problems)} figures fail the provenance check")
    print(f"provenance: {len(entries)} figures, every declared source under "
          f"{', '.join(ALLOWED_ROOTS)}")
    if args.check:
        return
    INDEX.write_text(render(entries), encoding="utf-8")
    print(f"wrote: {INDEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
